/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_ajouter_un_entraineur (void);
GtkWidget* create_modifer_un_entraineur (void);
GtkWidget* create_supprimer_un_entraineur (void);
GtkWidget* create_inscrire____un_cours_sportif (void);
GtkWidget* create_login_entraineur (void);
GtkWidget* create_window2 (void);
GtkWidget* create_login (void);
