/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *vbox3;
  GtkWidget *label1;
  GtkWidget *hbox2;
  GtkWidget *labelNom;
  GtkWidget *entryNom;
  GtkWidget *labelMarque;
  GtkWidget *entryMarque;
  GtkWidget *hbox3;
  GtkWidget *hbox4;
  GtkWidget *labelID;
  GtkWidget *entryID;
  GtkWidget *labelQuantit__;
  GtkObject *entryQuantite_adj;
  GtkWidget *entryQuantite;
  GtkWidget *hbox5;
  GtkWidget *labelCentreSportif;
  GtkWidget *vbox4;
  GtkWidget *vbox5;
  GtkWidget *label7;
  GtkWidget *entryCentreSportif;
  GtkWidget *label8;
  GtkWidget *vbox6;
  GtkWidget *labelDateAchat;
  GtkWidget *calendarDateAchat;
  GtkWidget *hbox6;
  GtkWidget *vbox7;
  GtkWidget *hbox7;
  GtkWidget *hbox8;
  GtkWidget *labelEtat;
  GtkWidget *checkbutton1;
  GtkWidget *hbox9;
  GtkWidget *labelType;
  GtkWidget *comboType;
  GtkWidget *hbox10;
  GtkWidget *hbox11;
  GtkWidget *hbox12;
  GtkWidget *hbox13;
  GtkWidget *labelUtilisation;
  GtkWidget *hbox14;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *labelPrix;
  GtkWidget *entryPrix;
  GtkWidget *hbox15;
  GtkWidget *vbox8;
  GtkWidget *hbox16;
  GtkWidget *vbox9;
  GtkWidget *hbox17;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox18;
  GtkWidget *image1;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *buttonEnregistrer;
  GtkWidget *alignment2;
  GtkWidget *hbox19;
  GtkWidget *image2;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox20;
  GtkWidget *image3;
  GtkWidget *label18;
  GtkWidget *image19;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("ajout"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (ajout), vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox3, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("<span foreground=\"green\" font_desc=\"Sans Bold 14\">Ajout des \303\251quipements</span>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox3), label1, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, TRUE, TRUE, 0);

  labelNom = gtk_label_new (_("nom de l'equipement"));
  gtk_widget_show (labelNom);
  gtk_box_pack_start (GTK_BOX (hbox2), labelNom, FALSE, FALSE, 0);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_box_pack_start (GTK_BOX (hbox2), entryNom, TRUE, TRUE, 15);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  labelMarque = gtk_label_new (_("Marque"));
  gtk_widget_show (labelMarque);
  gtk_box_pack_start (GTK_BOX (hbox2), labelMarque, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelMarque), TRUE);

  entryMarque = gtk_entry_new ();
  gtk_widget_show (entryMarque);
  gtk_box_pack_start (GTK_BOX (hbox2), entryMarque, TRUE, TRUE, 15);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMarque), 8226);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, TRUE, 31);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), hbox4, TRUE, TRUE, 0);

  labelID = gtk_label_new (_("ID:"));
  gtk_widget_show (labelID);
  gtk_box_pack_start (GTK_BOX (hbox4), labelID, TRUE, TRUE, 0);

  entryID = gtk_entry_new ();
  gtk_widget_show (entryID);
  gtk_box_pack_start (GTK_BOX (hbox4), entryID, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID), 8226);

  labelQuantit__ = gtk_label_new (_("Qauntit\303\251"));
  gtk_widget_show (labelQuantit__);
  gtk_box_pack_start (GTK_BOX (hbox3), labelQuantit__, TRUE, TRUE, 0);

  entryQuantite_adj = gtk_adjustment_new (4, 0, 100, 1, 10, 10);
  entryQuantite = gtk_spin_button_new (GTK_ADJUSTMENT (entryQuantite_adj), 1, 0);
  gtk_widget_show (entryQuantite);
  gtk_box_pack_start (GTK_BOX (hbox3), entryQuantite, TRUE, TRUE, 52);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, TRUE, TRUE, 0);

  labelCentreSportif = gtk_label_new (_("Centre sportif d'affectation "));
  gtk_widget_show (labelCentreSportif);
  gtk_box_pack_start (GTK_BOX (hbox5), labelCentreSportif, FALSE, FALSE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox4, TRUE, TRUE, 30);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox5, TRUE, TRUE, 0);

  label7 = gtk_label_new ("");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox5), label7, TRUE, TRUE, 0);

  entryCentreSportif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entryCentreSportif);
  gtk_box_pack_start (GTK_BOX (vbox5), entryCentreSportif, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entryCentreSportif), _("Centre 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entryCentreSportif), _("Centre 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entryCentreSportif), _("Centre 3"));

  label8 = gtk_label_new ("");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox5), label8, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox6, TRUE, TRUE, 170);

  labelDateAchat = gtk_label_new (_("Date d'achat"));
  gtk_widget_show (labelDateAchat);
  gtk_box_pack_start (GTK_BOX (vbox6), labelDateAchat, TRUE, FALSE, 0);

  calendarDateAchat = gtk_calendar_new ();
  gtk_widget_show (calendarDateAchat);
  gtk_box_pack_start (GTK_BOX (vbox6), calendarDateAchat, FALSE, FALSE, 0);
  gtk_widget_set_size_request (calendarDateAchat, -1, 79);
  gtk_calendar_display_options (GTK_CALENDAR (calendarDateAchat),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox6), vbox7, TRUE, TRUE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox7, TRUE, TRUE, 0);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (hbox7), hbox8, TRUE, TRUE, 0);

  labelEtat = gtk_label_new (_("Etat:"));
  gtk_widget_show (labelEtat);
  gtk_box_pack_start (GTK_BOX (hbox8), labelEtat, FALSE, FALSE, 30);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("nouveau"));
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (hbox8), checkbutton1, FALSE, FALSE, 200);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (hbox7), hbox9, TRUE, TRUE, 0);

  labelType = gtk_label_new (_("Type"));
  gtk_widget_show (labelType);
  gtk_box_pack_start (GTK_BOX (hbox9), labelType, TRUE, TRUE, 0);

  comboType = gtk_combo_box_new_text ();
  gtk_widget_show (comboType);
  gtk_box_pack_start (GTK_BOX (hbox9), comboType, TRUE, FALSE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboType), _("Cardio"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboType), _("Fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboType), _("Zumba"));

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox10, TRUE, TRUE, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (hbox10), hbox11, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (hbox11), hbox12, TRUE, TRUE, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (hbox12), hbox13, TRUE, TRUE, 0);

  labelUtilisation = gtk_label_new (_("Utilisation"));
  gtk_widget_show (labelUtilisation);
  gtk_box_pack_start (GTK_BOX (hbox13), labelUtilisation, TRUE, TRUE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (hbox13), hbox14, TRUE, TRUE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Aquatique"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton1, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Plain air"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton2, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Interieur"));
  gtk_widget_show (radiobutton3);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton3, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  labelPrix = gtk_label_new (_("Prix"));
  gtk_widget_show (labelPrix);
  gtk_box_pack_start (GTK_BOX (hbox12), labelPrix, TRUE, FALSE, 0);

  entryPrix = gtk_entry_new ();
  gtk_widget_show (entryPrix);
  gtk_box_pack_start (GTK_BOX (hbox12), entryPrix, TRUE, TRUE, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrix), 8226);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox15, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox15), vbox8, TRUE, TRUE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox16, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox16), vbox9, TRUE, TRUE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox17, TRUE, TRUE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox17), button1, TRUE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox18);

  image1 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox18), image1, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox18), label14, FALSE, FALSE, 0);

  label15 = gtk_label_new ("");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox17), label15, TRUE, TRUE, 0);

  buttonEnregistrer = gtk_button_new ();
  gtk_widget_show (buttonEnregistrer);
  gtk_box_pack_start (GTK_BOX (hbox17), buttonEnregistrer, TRUE, TRUE, 6);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonEnregistrer), alignment2);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox19);

  image2 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox19), image2, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox19), label16, FALSE, FALSE, 0);

  label17 = gtk_label_new ("");
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox17), label17, TRUE, TRUE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox17), button3, TRUE, FALSE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox20);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox20), image3, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox20), label18, FALSE, FALSE, 0);

  image19 = create_pixmap (ajout, "cceZq7Uw.jpeg");
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (vbox9), image19, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image19, -1, 151);

  g_signal_connect ((gpointer) buttonEnregistrer, "clicked",
                    G_CALLBACK (on_buttonEnregistrer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (ajout, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajout, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajout, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (ajout, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (ajout, labelMarque, "labelMarque");
  GLADE_HOOKUP_OBJECT (ajout, entryMarque, "entryMarque");
  GLADE_HOOKUP_OBJECT (ajout, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajout, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajout, labelID, "labelID");
  GLADE_HOOKUP_OBJECT (ajout, entryID, "entryID");
  GLADE_HOOKUP_OBJECT (ajout, labelQuantit__, "labelQuantit__");
  GLADE_HOOKUP_OBJECT (ajout, entryQuantite, "entryQuantite");
  GLADE_HOOKUP_OBJECT (ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajout, labelCentreSportif, "labelCentreSportif");
  GLADE_HOOKUP_OBJECT (ajout, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (ajout, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajout, entryCentreSportif, "entryCentreSportif");
  GLADE_HOOKUP_OBJECT (ajout, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajout, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (ajout, labelDateAchat, "labelDateAchat");
  GLADE_HOOKUP_OBJECT (ajout, calendarDateAchat, "calendarDateAchat");
  GLADE_HOOKUP_OBJECT (ajout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajout, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (ajout, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajout, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajout, labelEtat, "labelEtat");
  GLADE_HOOKUP_OBJECT (ajout, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (ajout, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajout, labelType, "labelType");
  GLADE_HOOKUP_OBJECT (ajout, comboType, "comboType");
  GLADE_HOOKUP_OBJECT (ajout, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ajout, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ajout, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ajout, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ajout, labelUtilisation, "labelUtilisation");
  GLADE_HOOKUP_OBJECT (ajout, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajout, labelPrix, "labelPrix");
  GLADE_HOOKUP_OBJECT (ajout, entryPrix, "entryPrix");
  GLADE_HOOKUP_OBJECT (ajout, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ajout, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (ajout, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajout, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (ajout, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (ajout, button1, "button1");
  GLADE_HOOKUP_OBJECT (ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajout, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajout, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajout, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajout, buttonEnregistrer, "buttonEnregistrer");
  GLADE_HOOKUP_OBJECT (ajout, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajout, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (ajout, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajout, label16, "label16");
  GLADE_HOOKUP_OBJECT (ajout, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajout, button3, "button3");
  GLADE_HOOKUP_OBJECT (ajout, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajout, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (ajout, image3, "image3");
  GLADE_HOOKUP_OBJECT (ajout, label18, "label18");
  GLADE_HOOKUP_OBJECT (ajout, image19, "image19");

  return ajout;
}

GtkWidget*
create_reservation (void)
{
  GtkWidget *reservation;
  GtkWidget *vbox10;
  GtkWidget *vbox11;
  GtkWidget *vbox12;
  GtkWidget *vbox49;
  GtkWidget *image20;
  GtkWidget *label102;
  GtkWidget *hbox21;
  GtkWidget *sreserve_labelNnom;
  GtkWidget *sreserveentryNom;
  GtkWidget *sreserve_labelMarque;
  GtkWidget *sreserveentryMarque;
  GtkWidget *hbox22;
  GtkWidget *hbox24;
  GtkWidget *sreserve_labelquantit__;
  GtkObject *sreservespinbuttonQuantite_adj;
  GtkWidget *sreservespinbuttonQuantite;
  GtkWidget *hbox25;
  GtkWidget *hbox26;
  GtkWidget *sreserve_laberDate;
  GtkWidget *vbox16;
  GtkWidget *label34;
  GtkWidget *sreservecalendar;
  GtkWidget *_;
  GtkWidget *hbox27;
  GtkWidget *label26;
  GtkWidget *hbox28;
  GtkWidget *sresere_labelHeuredebut;
  GtkWidget *sreserveentryHeuredebut;
  GtkWidget *hbox29;
  GtkWidget *sreserve_labelDuree;
  GtkWidget *vbox13;
  GtkWidget *sreservecheckbuttonDuree1;
  GtkWidget *sreservecheckbuttonDuree2;
  GtkWidget *sreservecheckbuttonDuree3;
  GtkWidget *vbox14;
  GtkWidget *hbox35;
  GtkWidget *image34;
  GtkWidget *vbox17;
  GtkWidget *sreserve_labelCentresportif;
  GtkWidget *label38;
  GtkWidget *vbox18;
  GtkWidget *sreservecomboboxentryCentre;
  GtkWidget *label39;
  GtkWidget *label37;
  GtkWidget *vbox50;
  GtkWidget *hbox100;
  GtkWidget *button20;
  GtkWidget *alignment19;
  GtkWidget *hbox101;
  GtkWidget *image21;
  GtkWidget *label103;
  GtkWidget *button21;
  GtkWidget *alignment20;
  GtkWidget *hbox102;
  GtkWidget *image22;
  GtkWidget *label104;
  GtkWidget *button22;
  GtkWidget *alignment21;
  GtkWidget *hbox103;
  GtkWidget *image23;
  GtkWidget *label105;
  GtkWidget *image24;

  reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reservation), _("reservation"));

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (reservation), vbox10);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (vbox10), vbox11, TRUE, TRUE, 0);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox11), vbox12, TRUE, TRUE, 0);

  vbox49 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox49);
  gtk_box_pack_start (GTK_BOX (vbox12), vbox49, TRUE, TRUE, 0);

  image20 = create_pixmap (reservation, "cceZq7Uw.jpeg");
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (vbox49), image20, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image20, 953, 25);

  label102 = gtk_label_new (_("<span foreground=\"green\" font_desc=\"sans bold 14\">R\303\251servation d'\303\251quipements</span>\n"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (vbox49), label102, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label102), TRUE);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox21, TRUE, TRUE, 0);

  sreserve_labelNnom = gtk_label_new (_("Nom de l'\303\251quipement"));
  gtk_widget_show (sreserve_labelNnom);
  gtk_box_pack_start (GTK_BOX (hbox21), sreserve_labelNnom, FALSE, FALSE, 0);

  sreserveentryNom = gtk_entry_new ();
  gtk_widget_show (sreserveentryNom);
  gtk_box_pack_start (GTK_BOX (hbox21), sreserveentryNom, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (sreserveentryNom), 8226);

  sreserve_labelMarque = gtk_label_new (_("Marque"));
  gtk_widget_show (sreserve_labelMarque);
  gtk_box_pack_start (GTK_BOX (hbox21), sreserve_labelMarque, TRUE, TRUE, 0);

  sreserveentryMarque = gtk_entry_new ();
  gtk_widget_show (sreserveentryMarque);
  gtk_box_pack_start (GTK_BOX (hbox21), sreserveentryMarque, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (sreserveentryMarque), 8226);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox22);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox22, FALSE, TRUE, 0);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox24);
  gtk_box_pack_start (GTK_BOX (hbox22), hbox24, TRUE, TRUE, 0);

  sreserve_labelquantit__ = gtk_label_new (_("Quantit\303\251"));
  gtk_widget_show (sreserve_labelquantit__);
  gtk_box_pack_start (GTK_BOX (hbox24), sreserve_labelquantit__, TRUE, FALSE, 20);

  sreservespinbuttonQuantite_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  sreservespinbuttonQuantite = gtk_spin_button_new (GTK_ADJUSTMENT (sreservespinbuttonQuantite_adj), 1, 0);
  gtk_widget_show (sreservespinbuttonQuantite);
  gtk_box_pack_start (GTK_BOX (hbox24), sreservespinbuttonQuantite, TRUE, TRUE, 25);

  hbox25 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox25);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox25, TRUE, TRUE, 0);

  hbox26 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (hbox25), hbox26, TRUE, TRUE, 0);

  sreserve_laberDate = gtk_label_new (_("Date"));
  gtk_widget_show (sreserve_laberDate);
  gtk_box_pack_start (GTK_BOX (hbox26), sreserve_laberDate, TRUE, TRUE, 0);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_box_pack_start (GTK_BOX (hbox26), vbox16, TRUE, TRUE, 23);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (vbox16), label34, TRUE, TRUE, 0);

  sreservecalendar = gtk_calendar_new ();
  gtk_widget_show (sreservecalendar);
  gtk_box_pack_start (GTK_BOX (vbox16), sreservecalendar, TRUE, TRUE, 0);
  gtk_calendar_display_options (GTK_CALENDAR (sreservecalendar),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  _ = gtk_label_new ("");
  gtk_widget_show (_);
  gtk_box_pack_start (GTK_BOX (vbox16), _, TRUE, TRUE, 0);

  hbox27 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox27);
  gtk_box_pack_start (GTK_BOX (hbox25), hbox27, TRUE, TRUE, 0);

  label26 = gtk_label_new ("");
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox27), label26, FALSE, FALSE, 0);

  hbox28 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox28);
  gtk_box_pack_start (GTK_BOX (hbox27), hbox28, TRUE, TRUE, 0);

  sresere_labelHeuredebut = gtk_label_new (_("Heure d\303\251but"));
  gtk_widget_show (sresere_labelHeuredebut);
  gtk_box_pack_start (GTK_BOX (hbox28), sresere_labelHeuredebut, TRUE, TRUE, 0);

  sreserveentryHeuredebut = gtk_entry_new ();
  gtk_widget_show (sreserveentryHeuredebut);
  gtk_box_pack_start (GTK_BOX (hbox28), sreserveentryHeuredebut, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (sreserveentryHeuredebut), 8226);

  hbox29 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox29);
  gtk_box_pack_start (GTK_BOX (hbox25), hbox29, TRUE, TRUE, 0);

  sreserve_labelDuree = gtk_label_new (_("Dur\303\251e"));
  gtk_widget_show (sreserve_labelDuree);
  gtk_box_pack_start (GTK_BOX (hbox29), sreserve_labelDuree, TRUE, TRUE, 0);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox29), vbox13, FALSE, FALSE, 0);

  sreservecheckbuttonDuree1 = gtk_check_button_new_with_mnemonic (_("1h"));
  gtk_widget_show (sreservecheckbuttonDuree1);
  gtk_box_pack_start (GTK_BOX (vbox13), sreservecheckbuttonDuree1, TRUE, TRUE, 0);

  sreservecheckbuttonDuree2 = gtk_check_button_new_with_mnemonic (_("1h30"));
  gtk_widget_show (sreservecheckbuttonDuree2);
  gtk_box_pack_start (GTK_BOX (vbox13), sreservecheckbuttonDuree2, TRUE, TRUE, 0);

  sreservecheckbuttonDuree3 = gtk_check_button_new_with_mnemonic (_("2h"));
  gtk_widget_show (sreservecheckbuttonDuree3);
  gtk_box_pack_start (GTK_BOX (vbox13), sreservecheckbuttonDuree3, TRUE, TRUE, 0);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (vbox10), vbox14, TRUE, TRUE, 0);

  hbox35 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox35);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox35, TRUE, TRUE, 0);

  image34 = create_pixmap (reservation, "VBl6O_zL.jpeg");
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox35), image34, TRUE, TRUE, 122);
  gtk_widget_set_size_request (image34, 180, 75);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (hbox35), vbox17, TRUE, TRUE, 0);

  sreserve_labelCentresportif = gtk_label_new (_("Centre sportif"));
  gtk_widget_show (sreserve_labelCentresportif);
  gtk_box_pack_start (GTK_BOX (vbox17), sreserve_labelCentresportif, TRUE, TRUE, 0);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (vbox17), label38, TRUE, TRUE, 0);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox18);
  gtk_box_pack_start (GTK_BOX (hbox35), vbox18, TRUE, TRUE, 0);

  sreservecomboboxentryCentre = gtk_combo_box_entry_new_text ();
  gtk_widget_show (sreservecomboboxentryCentre);
  gtk_box_pack_start (GTK_BOX (vbox18), sreservecomboboxentryCentre, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (sreservecomboboxentryCentre), _("Centre 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (sreservecomboboxentryCentre), _("Centre 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (sreservecomboboxentryCentre), _("Centre 3"));

  label39 = gtk_label_new ("");
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (vbox18), label39, TRUE, FALSE, 0);

  label37 = gtk_label_new ("");
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox35), label37, TRUE, TRUE, 0);

  vbox50 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox50);
  gtk_box_pack_start (GTK_BOX (vbox14), vbox50, TRUE, TRUE, 0);

  hbox100 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox100);
  gtk_box_pack_start (GTK_BOX (vbox50), hbox100, TRUE, TRUE, 0);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (hbox100), button20, TRUE, FALSE, 0);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button20), alignment19);

  hbox101 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox101);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox101);

  image21 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox101), image21, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox101), label103, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_box_pack_start (GTK_BOX (hbox100), button21, TRUE, TRUE, 0);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button21), alignment20);

  hbox102 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox102);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox102);

  image22 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox102), image22, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox102), label104, FALSE, FALSE, 0);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_box_pack_start (GTK_BOX (hbox100), button22, TRUE, FALSE, 0);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button22), alignment21);

  hbox103 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox103);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox103);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox103), image23, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox103), label105, FALSE, FALSE, 0);

  image24 = create_pixmap (reservation, "cceZq7Uw.jpeg");
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (vbox50), image24, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image24, -1, 5);

  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_sreserve_buttonPrecedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_sreserve_buttonEnregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_sreserve_buttonQuitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reservation, reservation, "reservation");
  GLADE_HOOKUP_OBJECT (reservation, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (reservation, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (reservation, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (reservation, vbox49, "vbox49");
  GLADE_HOOKUP_OBJECT (reservation, image20, "image20");
  GLADE_HOOKUP_OBJECT (reservation, label102, "label102");
  GLADE_HOOKUP_OBJECT (reservation, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (reservation, sreserve_labelNnom, "sreserve_labelNnom");
  GLADE_HOOKUP_OBJECT (reservation, sreserveentryNom, "sreserveentryNom");
  GLADE_HOOKUP_OBJECT (reservation, sreserve_labelMarque, "sreserve_labelMarque");
  GLADE_HOOKUP_OBJECT (reservation, sreserveentryMarque, "sreserveentryMarque");
  GLADE_HOOKUP_OBJECT (reservation, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (reservation, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (reservation, sreserve_labelquantit__, "sreserve_labelquantit__");
  GLADE_HOOKUP_OBJECT (reservation, sreservespinbuttonQuantite, "sreservespinbuttonQuantite");
  GLADE_HOOKUP_OBJECT (reservation, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (reservation, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (reservation, sreserve_laberDate, "sreserve_laberDate");
  GLADE_HOOKUP_OBJECT (reservation, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (reservation, label34, "label34");
  GLADE_HOOKUP_OBJECT (reservation, sreservecalendar, "sreservecalendar");
  GLADE_HOOKUP_OBJECT (reservation, _, "_");
  GLADE_HOOKUP_OBJECT (reservation, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (reservation, label26, "label26");
  GLADE_HOOKUP_OBJECT (reservation, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (reservation, sresere_labelHeuredebut, "sresere_labelHeuredebut");
  GLADE_HOOKUP_OBJECT (reservation, sreserveentryHeuredebut, "sreserveentryHeuredebut");
  GLADE_HOOKUP_OBJECT (reservation, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (reservation, sreserve_labelDuree, "sreserve_labelDuree");
  GLADE_HOOKUP_OBJECT (reservation, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (reservation, sreservecheckbuttonDuree1, "sreservecheckbuttonDuree1");
  GLADE_HOOKUP_OBJECT (reservation, sreservecheckbuttonDuree2, "sreservecheckbuttonDuree2");
  GLADE_HOOKUP_OBJECT (reservation, sreservecheckbuttonDuree3, "sreservecheckbuttonDuree3");
  GLADE_HOOKUP_OBJECT (reservation, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (reservation, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (reservation, image34, "image34");
  GLADE_HOOKUP_OBJECT (reservation, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (reservation, sreserve_labelCentresportif, "sreserve_labelCentresportif");
  GLADE_HOOKUP_OBJECT (reservation, label38, "label38");
  GLADE_HOOKUP_OBJECT (reservation, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (reservation, sreservecomboboxentryCentre, "sreservecomboboxentryCentre");
  GLADE_HOOKUP_OBJECT (reservation, label39, "label39");
  GLADE_HOOKUP_OBJECT (reservation, label37, "label37");
  GLADE_HOOKUP_OBJECT (reservation, vbox50, "vbox50");
  GLADE_HOOKUP_OBJECT (reservation, hbox100, "hbox100");
  GLADE_HOOKUP_OBJECT (reservation, button20, "button20");
  GLADE_HOOKUP_OBJECT (reservation, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (reservation, hbox101, "hbox101");
  GLADE_HOOKUP_OBJECT (reservation, image21, "image21");
  GLADE_HOOKUP_OBJECT (reservation, label103, "label103");
  GLADE_HOOKUP_OBJECT (reservation, button21, "button21");
  GLADE_HOOKUP_OBJECT (reservation, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (reservation, hbox102, "hbox102");
  GLADE_HOOKUP_OBJECT (reservation, image22, "image22");
  GLADE_HOOKUP_OBJECT (reservation, label104, "label104");
  GLADE_HOOKUP_OBJECT (reservation, button22, "button22");
  GLADE_HOOKUP_OBJECT (reservation, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (reservation, hbox103, "hbox103");
  GLADE_HOOKUP_OBJECT (reservation, image23, "image23");
  GLADE_HOOKUP_OBJECT (reservation, label105, "label105");
  GLADE_HOOKUP_OBJECT (reservation, image24, "image24");

  return reservation;
}

GtkWidget*
create_modification (void)
{
  GtkWidget *modification;
  GtkWidget *vbox19;
  GtkWidget *hbox36;
  GtkWidget *alignment7;
  GtkWidget *hbox37;
  GtkWidget *label40;
  GtkWidget *vbox51;
  GtkWidget *image26;
  GtkWidget *vbox52;
  GtkWidget *vbox53;
  GtkWidget *label106;
  GtkWidget *vbox22;
  GtkWidget *vbox23;
  GtkWidget *hbox47;
  GtkWidget *vbox24;
  GtkWidget *hbox48;
  GtkWidget *smodiflabelNom;
  GtkWidget *smodifentryNom;
  GtkWidget *smodiflabelMarque;
  GtkWidget *smodifentryMarque;
  GtkWidget *hbox49;
  GtkWidget *hbox50;
  GtkWidget *smodiflabelId;
  GtkWidget *smodifentryId;
  GtkWidget *smodiflabelQuantite;
  GtkObject *smodifspinbuttonQuantite_adj;
  GtkWidget *smodifspinbuttonQuantite;
  GtkWidget *hbox51;
  GtkWidget *smodiflabelCentre;
  GtkWidget *vbox25;
  GtkWidget *vbox26;
  GtkWidget *label58;
  GtkWidget *smodifcomboboxentryCentre;
  GtkWidget *label59;
  GtkWidget *vbox27;
  GtkWidget *smodiflabelDate;
  GtkWidget *smodifcalendarDate;
  GtkWidget *hbox52;
  GtkWidget *vbox28;
  GtkWidget *hbox53;
  GtkWidget *hbox54;
  GtkWidget *smodiflabelEtat;
  GtkWidget *smodifcheckbuttonEtat;
  GtkWidget *hbox55;
  GtkWidget *smodiflabelType;
  GtkWidget *smodifcomboboxType;
  GtkWidget *hbox56;
  GtkWidget *hbox57;
  GtkWidget *hbox58;
  GtkWidget *hbox59;
  GtkWidget *smodiflabelUtilisation;
  GtkWidget *hbox60;
  GtkWidget *smodifradiobuttonUtilisation1;
  GSList *smodifradiobuttonUtilisation1_group = NULL;
  GtkWidget *smodifradiobuttonUtilisation2;
  GSList *smodifradiobuttonUtilisation2_group = NULL;
  GtkWidget *smodifradiobuttonUtilisation3;
  GSList *smodifradiobuttonUtilisation3_group = NULL;
  GtkWidget *smodiflabelPrix;
  GtkWidget *smodifentryPrix;
  GtkWidget *hbox61;
  GtkWidget *vbox29;
  GtkWidget *hbox62;
  GtkWidget *vbox30;
  GtkWidget *hbox63;
  GtkWidget *smodifbuttonPrecedent;
  GtkWidget *alignment10;
  GtkWidget *hbox64;
  GtkWidget *image9;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *button19;
  GtkWidget *alignment18;
  GtkWidget *hbox99;
  GtkWidget *image18;
  GtkWidget *label101;
  GtkWidget *label68;
  GtkWidget *smodifbuttonQuitter;
  GtkWidget *alignment12;
  GtkWidget *hbox66;
  GtkWidget *image11;
  GtkWidget *label69;
  GtkWidget *image25;

  modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modification), _("modification"));

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_container_add (GTK_CONTAINER (modification), vbox19);

  hbox36 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox36);
  gtk_box_pack_start (GTK_BOX (vbox19), hbox36, TRUE, TRUE, 0);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_box_pack_start (GTK_BOX (hbox36), alignment7, TRUE, TRUE, 0);

  hbox37 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox37);

  label40 = gtk_label_new ("");
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox37), label40, FALSE, FALSE, 0);

  vbox51 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox51);
  gtk_box_pack_start (GTK_BOX (hbox37), vbox51, TRUE, TRUE, 0);

  image26 = create_pixmap (modification, "_KDfbkyk.jpeg");
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (vbox51), image26, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image26, -1, 1);

  vbox52 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox52);
  gtk_box_pack_start (GTK_BOX (vbox51), vbox52, FALSE, TRUE, 0);

  vbox53 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox53);
  gtk_box_pack_start (GTK_BOX (vbox52), vbox53, FALSE, FALSE, 0);

  label106 = gtk_label_new (_("<span foreground=\"green\" font_desc=\"sans bold 14\">Modification des \303\251quipements</span>\n"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (vbox53), label106, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label106), TRUE);

  vbox22 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox22);
  gtk_box_pack_start (GTK_BOX (vbox19), vbox22, TRUE, TRUE, 0);

  vbox23 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox23);
  gtk_box_pack_start (GTK_BOX (vbox22), vbox23, TRUE, TRUE, 0);

  hbox47 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox47);
  gtk_box_pack_start (GTK_BOX (vbox23), hbox47, TRUE, TRUE, 0);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox24);
  gtk_box_pack_start (GTK_BOX (hbox47), vbox24, TRUE, TRUE, 0);

  hbox48 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox48);
  gtk_box_pack_start (GTK_BOX (vbox24), hbox48, TRUE, TRUE, 0);

  smodiflabelNom = gtk_label_new (_("nom de l'equipement"));
  gtk_widget_show (smodiflabelNom);
  gtk_box_pack_start (GTK_BOX (hbox48), smodiflabelNom, FALSE, FALSE, 0);

  smodifentryNom = gtk_entry_new ();
  gtk_widget_show (smodifentryNom);
  gtk_box_pack_start (GTK_BOX (hbox48), smodifentryNom, TRUE, TRUE, 15);
  gtk_entry_set_invisible_char (GTK_ENTRY (smodifentryNom), 8226);

  smodiflabelMarque = gtk_label_new (_("Marque"));
  gtk_widget_show (smodiflabelMarque);
  gtk_box_pack_start (GTK_BOX (hbox48), smodiflabelMarque, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (smodiflabelMarque), TRUE);

  smodifentryMarque = gtk_entry_new ();
  gtk_widget_show (smodifentryMarque);
  gtk_box_pack_start (GTK_BOX (hbox48), smodifentryMarque, TRUE, TRUE, 15);
  gtk_entry_set_invisible_char (GTK_ENTRY (smodifentryMarque), 8226);

  hbox49 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox49);
  gtk_box_pack_start (GTK_BOX (vbox22), hbox49, FALSE, TRUE, 31);

  hbox50 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox50);
  gtk_box_pack_start (GTK_BOX (hbox49), hbox50, TRUE, TRUE, 0);

  smodiflabelId = gtk_label_new (_("ID:"));
  gtk_widget_show (smodiflabelId);
  gtk_box_pack_start (GTK_BOX (hbox50), smodiflabelId, TRUE, TRUE, 0);

  smodifentryId = gtk_entry_new ();
  gtk_widget_show (smodifentryId);
  gtk_box_pack_start (GTK_BOX (hbox50), smodifentryId, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (smodifentryId), 8226);

  smodiflabelQuantite = gtk_label_new (_("Qauntit\303\251"));
  gtk_widget_show (smodiflabelQuantite);
  gtk_box_pack_start (GTK_BOX (hbox49), smodiflabelQuantite, TRUE, TRUE, 0);

  smodifspinbuttonQuantite_adj = gtk_adjustment_new (4, 0, 100, 1, 10, 10);
  smodifspinbuttonQuantite = gtk_spin_button_new (GTK_ADJUSTMENT (smodifspinbuttonQuantite_adj), 1, 0);
  gtk_widget_show (smodifspinbuttonQuantite);
  gtk_box_pack_start (GTK_BOX (hbox49), smodifspinbuttonQuantite, TRUE, TRUE, 52);

  hbox51 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox51);
  gtk_box_pack_start (GTK_BOX (vbox22), hbox51, TRUE, TRUE, 0);

  smodiflabelCentre = gtk_label_new (_("Centre sportif d'affectation "));
  gtk_widget_show (smodiflabelCentre);
  gtk_box_pack_start (GTK_BOX (hbox51), smodiflabelCentre, FALSE, FALSE, 0);

  vbox25 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox25);
  gtk_box_pack_start (GTK_BOX (hbox51), vbox25, TRUE, TRUE, 30);

  vbox26 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox26);
  gtk_box_pack_start (GTK_BOX (vbox25), vbox26, TRUE, TRUE, 0);

  label58 = gtk_label_new ("");
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (vbox26), label58, TRUE, TRUE, 0);

  smodifcomboboxentryCentre = gtk_combo_box_entry_new_text ();
  gtk_widget_show (smodifcomboboxentryCentre);
  gtk_box_pack_start (GTK_BOX (vbox26), smodifcomboboxentryCentre, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (smodifcomboboxentryCentre), _("Centre 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (smodifcomboboxentryCentre), _("Centre 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (smodifcomboboxentryCentre), _("Centre 3"));

  label59 = gtk_label_new ("");
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (vbox26), label59, TRUE, TRUE, 0);

  vbox27 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox27);
  gtk_box_pack_start (GTK_BOX (hbox51), vbox27, TRUE, TRUE, 170);

  smodiflabelDate = gtk_label_new (_("Date d'achat"));
  gtk_widget_show (smodiflabelDate);
  gtk_box_pack_start (GTK_BOX (vbox27), smodiflabelDate, TRUE, FALSE, 0);

  smodifcalendarDate = gtk_calendar_new ();
  gtk_widget_show (smodifcalendarDate);
  gtk_box_pack_start (GTK_BOX (vbox27), smodifcalendarDate, FALSE, FALSE, 0);
  gtk_widget_set_size_request (smodifcalendarDate, -1, 79);
  gtk_calendar_display_options (GTK_CALENDAR (smodifcalendarDate),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  hbox52 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox52);
  gtk_box_pack_start (GTK_BOX (vbox22), hbox52, TRUE, TRUE, 0);

  vbox28 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox28);
  gtk_box_pack_start (GTK_BOX (hbox52), vbox28, TRUE, TRUE, 0);

  hbox53 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox53);
  gtk_box_pack_start (GTK_BOX (vbox28), hbox53, TRUE, TRUE, 0);

  hbox54 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox54);
  gtk_box_pack_start (GTK_BOX (hbox53), hbox54, TRUE, TRUE, 0);

  smodiflabelEtat = gtk_label_new (_("Etat:"));
  gtk_widget_show (smodiflabelEtat);
  gtk_box_pack_start (GTK_BOX (hbox54), smodiflabelEtat, FALSE, FALSE, 30);

  smodifcheckbuttonEtat = gtk_check_button_new_with_mnemonic (_("nouveau"));
  gtk_widget_show (smodifcheckbuttonEtat);
  gtk_box_pack_start (GTK_BOX (hbox54), smodifcheckbuttonEtat, FALSE, FALSE, 200);

  hbox55 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox55);
  gtk_box_pack_start (GTK_BOX (hbox53), hbox55, TRUE, TRUE, 0);

  smodiflabelType = gtk_label_new (_("Type"));
  gtk_widget_show (smodiflabelType);
  gtk_box_pack_start (GTK_BOX (hbox55), smodiflabelType, TRUE, TRUE, 0);

  smodifcomboboxType = gtk_combo_box_new_text ();
  gtk_widget_show (smodifcomboboxType);
  gtk_box_pack_start (GTK_BOX (hbox55), smodifcomboboxType, TRUE, FALSE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (smodifcomboboxType), _("Cardio"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (smodifcomboboxType), _("Fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (smodifcomboboxType), _("Zumba"));

  hbox56 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox56);
  gtk_box_pack_start (GTK_BOX (vbox28), hbox56, TRUE, TRUE, 0);

  hbox57 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox57);
  gtk_box_pack_start (GTK_BOX (hbox56), hbox57, TRUE, TRUE, 0);

  hbox58 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox58);
  gtk_box_pack_start (GTK_BOX (hbox57), hbox58, TRUE, TRUE, 0);

  hbox59 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox59);
  gtk_box_pack_start (GTK_BOX (hbox58), hbox59, TRUE, TRUE, 0);

  smodiflabelUtilisation = gtk_label_new (_("Utilisation"));
  gtk_widget_show (smodiflabelUtilisation);
  gtk_box_pack_start (GTK_BOX (hbox59), smodiflabelUtilisation, TRUE, TRUE, 0);

  hbox60 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox60);
  gtk_box_pack_start (GTK_BOX (hbox59), hbox60, TRUE, TRUE, 0);

  smodifradiobuttonUtilisation1 = gtk_radio_button_new_with_mnemonic (NULL, _("Aquatique"));
  gtk_widget_show (smodifradiobuttonUtilisation1);
  gtk_box_pack_start (GTK_BOX (hbox60), smodifradiobuttonUtilisation1, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (smodifradiobuttonUtilisation1), smodifradiobuttonUtilisation1_group);
  smodifradiobuttonUtilisation1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (smodifradiobuttonUtilisation1));

  smodifradiobuttonUtilisation2 = gtk_radio_button_new_with_mnemonic (NULL, _("Plain air"));
  gtk_widget_show (smodifradiobuttonUtilisation2);
  gtk_box_pack_start (GTK_BOX (hbox60), smodifradiobuttonUtilisation2, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (smodifradiobuttonUtilisation2), smodifradiobuttonUtilisation2_group);
  smodifradiobuttonUtilisation2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (smodifradiobuttonUtilisation2));

  smodifradiobuttonUtilisation3 = gtk_radio_button_new_with_mnemonic (NULL, _("Interieur"));
  gtk_widget_show (smodifradiobuttonUtilisation3);
  gtk_box_pack_start (GTK_BOX (hbox60), smodifradiobuttonUtilisation3, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (smodifradiobuttonUtilisation3), smodifradiobuttonUtilisation3_group);
  smodifradiobuttonUtilisation3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (smodifradiobuttonUtilisation3));

  smodiflabelPrix = gtk_label_new (_("Prix"));
  gtk_widget_show (smodiflabelPrix);
  gtk_box_pack_start (GTK_BOX (hbox58), smodiflabelPrix, TRUE, FALSE, 0);

  smodifentryPrix = gtk_entry_new ();
  gtk_widget_show (smodifentryPrix);
  gtk_box_pack_start (GTK_BOX (hbox58), smodifentryPrix, TRUE, TRUE, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (smodifentryPrix), 8226);

  hbox61 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox61);
  gtk_box_pack_start (GTK_BOX (vbox22), hbox61, TRUE, TRUE, 0);

  vbox29 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox29);
  gtk_box_pack_start (GTK_BOX (hbox61), vbox29, TRUE, TRUE, 0);

  hbox62 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox62);
  gtk_box_pack_start (GTK_BOX (vbox29), hbox62, TRUE, TRUE, 0);

  vbox30 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox30);
  gtk_box_pack_start (GTK_BOX (hbox62), vbox30, TRUE, TRUE, 0);

  hbox63 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox63);
  gtk_box_pack_start (GTK_BOX (vbox30), hbox63, TRUE, TRUE, 0);

  smodifbuttonPrecedent = gtk_button_new ();
  gtk_widget_show (smodifbuttonPrecedent);
  gtk_box_pack_start (GTK_BOX (hbox63), smodifbuttonPrecedent, TRUE, FALSE, 0);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (smodifbuttonPrecedent), alignment10);

  hbox64 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox64);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox64);

  image9 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox64), image9, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox64), label65, FALSE, FALSE, 0);

  label66 = gtk_label_new ("");
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox63), label66, TRUE, TRUE, 0);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (hbox63), button19, TRUE, TRUE, 6);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button19), alignment18);

  hbox99 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox99);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox99);

  image18 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox99), image18, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox99), label101, FALSE, FALSE, 0);

  label68 = gtk_label_new ("");
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox63), label68, TRUE, TRUE, 0);

  smodifbuttonQuitter = gtk_button_new ();
  gtk_widget_show (smodifbuttonQuitter);
  gtk_box_pack_start (GTK_BOX (hbox63), smodifbuttonQuitter, TRUE, FALSE, 0);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (smodifbuttonQuitter), alignment12);

  hbox66 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox66);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox66);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox66), image11, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox66), label69, FALSE, FALSE, 0);

  image25 = create_pixmap (modification, "_KDfbkyk.jpeg");
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (vbox30), image25, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image25, -1, 1);

  g_signal_connect ((gpointer) smodifbuttonPrecedent, "clicked",
                    G_CALLBACK (on_smodifbuttonPrecedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_smodifbuttonEnregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) smodifbuttonQuitter, "clicked",
                    G_CALLBACK (on_smodifbuttonQuitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modification, modification, "modification");
  GLADE_HOOKUP_OBJECT (modification, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (modification, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (modification, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modification, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (modification, label40, "label40");
  GLADE_HOOKUP_OBJECT (modification, vbox51, "vbox51");
  GLADE_HOOKUP_OBJECT (modification, image26, "image26");
  GLADE_HOOKUP_OBJECT (modification, vbox52, "vbox52");
  GLADE_HOOKUP_OBJECT (modification, vbox53, "vbox53");
  GLADE_HOOKUP_OBJECT (modification, label106, "label106");
  GLADE_HOOKUP_OBJECT (modification, vbox22, "vbox22");
  GLADE_HOOKUP_OBJECT (modification, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (modification, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (modification, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (modification, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelNom, "smodiflabelNom");
  GLADE_HOOKUP_OBJECT (modification, smodifentryNom, "smodifentryNom");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelMarque, "smodiflabelMarque");
  GLADE_HOOKUP_OBJECT (modification, smodifentryMarque, "smodifentryMarque");
  GLADE_HOOKUP_OBJECT (modification, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (modification, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelId, "smodiflabelId");
  GLADE_HOOKUP_OBJECT (modification, smodifentryId, "smodifentryId");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelQuantite, "smodiflabelQuantite");
  GLADE_HOOKUP_OBJECT (modification, smodifspinbuttonQuantite, "smodifspinbuttonQuantite");
  GLADE_HOOKUP_OBJECT (modification, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelCentre, "smodiflabelCentre");
  GLADE_HOOKUP_OBJECT (modification, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (modification, vbox26, "vbox26");
  GLADE_HOOKUP_OBJECT (modification, label58, "label58");
  GLADE_HOOKUP_OBJECT (modification, smodifcomboboxentryCentre, "smodifcomboboxentryCentre");
  GLADE_HOOKUP_OBJECT (modification, label59, "label59");
  GLADE_HOOKUP_OBJECT (modification, vbox27, "vbox27");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelDate, "smodiflabelDate");
  GLADE_HOOKUP_OBJECT (modification, smodifcalendarDate, "smodifcalendarDate");
  GLADE_HOOKUP_OBJECT (modification, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (modification, vbox28, "vbox28");
  GLADE_HOOKUP_OBJECT (modification, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (modification, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelEtat, "smodiflabelEtat");
  GLADE_HOOKUP_OBJECT (modification, smodifcheckbuttonEtat, "smodifcheckbuttonEtat");
  GLADE_HOOKUP_OBJECT (modification, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelType, "smodiflabelType");
  GLADE_HOOKUP_OBJECT (modification, smodifcomboboxType, "smodifcomboboxType");
  GLADE_HOOKUP_OBJECT (modification, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (modification, hbox57, "hbox57");
  GLADE_HOOKUP_OBJECT (modification, hbox58, "hbox58");
  GLADE_HOOKUP_OBJECT (modification, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelUtilisation, "smodiflabelUtilisation");
  GLADE_HOOKUP_OBJECT (modification, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (modification, smodifradiobuttonUtilisation1, "smodifradiobuttonUtilisation1");
  GLADE_HOOKUP_OBJECT (modification, smodifradiobuttonUtilisation2, "smodifradiobuttonUtilisation2");
  GLADE_HOOKUP_OBJECT (modification, smodifradiobuttonUtilisation3, "smodifradiobuttonUtilisation3");
  GLADE_HOOKUP_OBJECT (modification, smodiflabelPrix, "smodiflabelPrix");
  GLADE_HOOKUP_OBJECT (modification, smodifentryPrix, "smodifentryPrix");
  GLADE_HOOKUP_OBJECT (modification, hbox61, "hbox61");
  GLADE_HOOKUP_OBJECT (modification, vbox29, "vbox29");
  GLADE_HOOKUP_OBJECT (modification, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (modification, vbox30, "vbox30");
  GLADE_HOOKUP_OBJECT (modification, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (modification, smodifbuttonPrecedent, "smodifbuttonPrecedent");
  GLADE_HOOKUP_OBJECT (modification, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modification, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (modification, image9, "image9");
  GLADE_HOOKUP_OBJECT (modification, label65, "label65");
  GLADE_HOOKUP_OBJECT (modification, label66, "label66");
  GLADE_HOOKUP_OBJECT (modification, button19, "button19");
  GLADE_HOOKUP_OBJECT (modification, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (modification, hbox99, "hbox99");
  GLADE_HOOKUP_OBJECT (modification, image18, "image18");
  GLADE_HOOKUP_OBJECT (modification, label101, "label101");
  GLADE_HOOKUP_OBJECT (modification, label68, "label68");
  GLADE_HOOKUP_OBJECT (modification, smodifbuttonQuitter, "smodifbuttonQuitter");
  GLADE_HOOKUP_OBJECT (modification, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modification, hbox66, "hbox66");
  GLADE_HOOKUP_OBJECT (modification, image11, "image11");
  GLADE_HOOKUP_OBJECT (modification, label69, "label69");
  GLADE_HOOKUP_OBJECT (modification, image25, "image25");

  return modification;
}

GtkWidget*
create_swarn (void)
{
  GtkWidget *swarn;
  GtkWidget *vbox40;
  GtkWidget *hbox87;
  GtkWidget *swarnlabelWarning;
  GtkWidget *hbuttonbox1;
  GtkWidget *swarnbuttonCancel;
  GtkWidget *Swarnbuttonok;

  swarn = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (swarn), _("warning"));
  gtk_window_set_type_hint (GTK_WINDOW (swarn), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (swarn), FALSE);

  vbox40 = GTK_DIALOG (swarn)->vbox;
  gtk_widget_show (vbox40);

  hbox87 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox87);
  gtk_box_pack_start (GTK_BOX (vbox40), hbox87, TRUE, TRUE, 0);

  swarnlabelWarning = gtk_label_new (_("<span foreground=\"red\" font_desc=\"sans bold 16\">Etes-vous sure de vouloir supprimer cet \303\251quipements</span>"));
  gtk_widget_show (swarnlabelWarning);
  gtk_box_pack_start (GTK_BOX (hbox87), swarnlabelWarning, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (swarnlabelWarning), TRUE);

  hbuttonbox1 = GTK_DIALOG (swarn)->action_area;
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  swarnbuttonCancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (swarnbuttonCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (swarn), swarnbuttonCancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (swarnbuttonCancel, GTK_CAN_DEFAULT);

  Swarnbuttonok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (Swarnbuttonok);
  gtk_dialog_add_action_widget (GTK_DIALOG (swarn), Swarnbuttonok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (Swarnbuttonok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) swarnbuttonCancel, "clicked",
                    G_CALLBACK (on_swarnbuttonCancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) Swarnbuttonok, "clicked",
                    G_CALLBACK (on_Swarnbuttonok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (swarn, swarn, "swarn");
  GLADE_HOOKUP_OBJECT_NO_REF (swarn, vbox40, "vbox40");
  GLADE_HOOKUP_OBJECT (swarn, hbox87, "hbox87");
  GLADE_HOOKUP_OBJECT (swarn, swarnlabelWarning, "swarnlabelWarning");
  GLADE_HOOKUP_OBJECT_NO_REF (swarn, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (swarn, swarnbuttonCancel, "swarnbuttonCancel");
  GLADE_HOOKUP_OBJECT (swarn, Swarnbuttonok, "Swarnbuttonok");

  return swarn;
}

GtkWidget*
create_recherche (void)
{
  GtkWidget *recherche;
  GtkWidget *vbox41;
  GtkWidget *vbox42;
  GtkWidget *vbox43;
  GtkWidget *hbox88;
  GtkWidget *hbox89;
  GtkWidget *label91;
  GtkWidget *vbox44;
  GtkWidget *hbox90;
  GtkWidget *image12;
  GtkWidget *scherlabelTitre;
  GtkWidget *shcerentryNom;
  GtkWidget *image33;
  GtkWidget *hbox91;
  GtkWidget *vbox45;
  GtkWidget *scrolledwindow2;
  GtkWidget *schertreeviewChercher;
  GtkWidget *hbox92;
  GtkWidget *vbox54;
  GtkWidget *hbox104;
  GtkWidget *vbox55;
  GtkWidget *button23;
  GtkWidget *alignment22;
  GtkWidget *hbox105;
  GtkWidget *image27;
  GtkWidget *label107;
  GtkWidget *hbox106;
  GtkWidget *button24;
  GtkWidget *alignment23;
  GtkWidget *hbox107;
  GtkWidget *image28;
  GtkWidget *label108;
  GtkWidget *button25;
  GtkWidget *alignment24;
  GtkWidget *hbox108;
  GtkWidget *image29;
  GtkWidget *label109;
  GtkWidget *vbox56;
  GtkWidget *button26;
  GtkWidget *alignment25;
  GtkWidget *hbox109;
  GtkWidget *image30;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkWidget *vbox57;
  GtkWidget *button27;
  GtkWidget *alignment26;
  GtkWidget *hbox110;
  GtkWidget *image31;
  GtkWidget *label112;
  GtkWidget *label113;
  GtkWidget *image32;

  recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (recherche), _("Recherce d'equipement"));

  vbox41 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox41);
  gtk_container_add (GTK_CONTAINER (recherche), vbox41);

  vbox42 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox42);
  gtk_box_pack_start (GTK_BOX (vbox41), vbox42, TRUE, TRUE, 0);

  vbox43 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox43);
  gtk_box_pack_start (GTK_BOX (vbox42), vbox43, FALSE, FALSE, 22);

  hbox88 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox88);
  gtk_box_pack_start (GTK_BOX (vbox43), hbox88, TRUE, TRUE, 0);

  hbox89 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox89);
  gtk_box_pack_start (GTK_BOX (hbox88), hbox89, TRUE, TRUE, 0);

  label91 = gtk_label_new ("");
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox89), label91, TRUE, TRUE, 0);

  vbox44 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox44);
  gtk_box_pack_start (GTK_BOX (hbox89), vbox44, TRUE, TRUE, 0);

  hbox90 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox90);
  gtk_box_pack_start (GTK_BOX (vbox44), hbox90, TRUE, TRUE, 0);

  image12 = gtk_image_new_from_icon_name ("gtk-zoom-fit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox90), image12, TRUE, TRUE, 0);

  scherlabelTitre = gtk_label_new (_("<span foreground=\"green\" font_desc=\"sans bold 12\">Chercher  le nom d'un \303\251quipement</span>\n"));
  gtk_widget_show (scherlabelTitre);
  gtk_box_pack_start (GTK_BOX (hbox90), scherlabelTitre, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (scherlabelTitre), TRUE);

  shcerentryNom = gtk_entry_new ();
  gtk_widget_show (shcerentryNom);
  gtk_box_pack_start (GTK_BOX (vbox44), shcerentryNom, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (shcerentryNom), 8226);

  image33 = create_pixmap (recherche, "VBl6O_zL.jpeg");
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox89), image33, TRUE, TRUE, 0);

  hbox91 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox91);
  gtk_box_pack_start (GTK_BOX (vbox42), hbox91, TRUE, TRUE, 0);

  vbox45 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox45);
  gtk_box_pack_start (GTK_BOX (hbox91), vbox45, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox45), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  schertreeviewChercher = gtk_tree_view_new ();
  gtk_widget_show (schertreeviewChercher);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), schertreeviewChercher);
  gtk_widget_set_size_request (schertreeviewChercher, -1, 317);

  hbox92 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox92);
  gtk_box_pack_start (GTK_BOX (vbox45), hbox92, TRUE, TRUE, 0);

  vbox54 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox54);
  gtk_box_pack_start (GTK_BOX (hbox92), vbox54, TRUE, TRUE, 0);

  hbox104 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox104);
  gtk_box_pack_start (GTK_BOX (vbox54), hbox104, TRUE, TRUE, 0);

  vbox55 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox55);
  gtk_box_pack_start (GTK_BOX (hbox104), vbox55, TRUE, TRUE, 0);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_box_pack_start (GTK_BOX (vbox55), button23, TRUE, FALSE, 0);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button23), alignment22);

  hbox105 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox105);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox105);

  image27 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox105), image27, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox105), label107, FALSE, FALSE, 0);

  hbox106 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox106);
  gtk_box_pack_start (GTK_BOX (vbox55), hbox106, TRUE, FALSE, 0);

  button24 = gtk_button_new ();
  gtk_widget_show (button24);
  gtk_box_pack_start (GTK_BOX (hbox106), button24, FALSE, FALSE, 0);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button24), alignment23);

  hbox107 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox107);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox107);

  image28 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox107), image28, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox107), label108, FALSE, FALSE, 0);

  button25 = gtk_button_new ();
  gtk_widget_show (button25);
  gtk_box_pack_start (GTK_BOX (hbox106), button25, FALSE, FALSE, 0);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button25), alignment24);

  hbox108 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox108);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox108);

  image29 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox108), image29, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox108), label109, FALSE, FALSE, 0);

  vbox56 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox56);
  gtk_box_pack_start (GTK_BOX (hbox104), vbox56, TRUE, TRUE, 0);

  button26 = gtk_button_new ();
  gtk_widget_show (button26);
  gtk_box_pack_start (GTK_BOX (vbox56), button26, TRUE, FALSE, 0);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button26), alignment25);

  hbox109 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox109);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox109);

  image30 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox109), image30, FALSE, FALSE, 0);

  label110 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (hbox109), label110, FALSE, FALSE, 0);

  label111 = gtk_label_new ("");
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (vbox56), label111, TRUE, TRUE, 0);

  vbox57 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox57);
  gtk_box_pack_start (GTK_BOX (hbox104), vbox57, TRUE, TRUE, 0);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_box_pack_start (GTK_BOX (vbox57), button27, TRUE, FALSE, 0);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button27), alignment26);

  hbox110 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox110);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox110);

  image31 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox110), image31, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox110), label112, FALSE, FALSE, 0);

  label113 = gtk_label_new ("");
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (vbox57), label113, TRUE, TRUE, 0);

  image32 = create_pixmap (recherche, "cceZq7Uw.jpeg");
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (vbox54), image32, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image32, -1, 231);

  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_scherbuttonChercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_scherbuttonPrecedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25, "clicked",
                    G_CALLBACK (on_scherbuttonQuitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26, "clicked",
                    G_CALLBACK (on_scherbuttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27, "clicked",
                    G_CALLBACK (on_scherbuttonSupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (recherche, vbox41, "vbox41");
  GLADE_HOOKUP_OBJECT (recherche, vbox42, "vbox42");
  GLADE_HOOKUP_OBJECT (recherche, vbox43, "vbox43");
  GLADE_HOOKUP_OBJECT (recherche, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (recherche, hbox89, "hbox89");
  GLADE_HOOKUP_OBJECT (recherche, label91, "label91");
  GLADE_HOOKUP_OBJECT (recherche, vbox44, "vbox44");
  GLADE_HOOKUP_OBJECT (recherche, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (recherche, image12, "image12");
  GLADE_HOOKUP_OBJECT (recherche, scherlabelTitre, "scherlabelTitre");
  GLADE_HOOKUP_OBJECT (recherche, shcerentryNom, "shcerentryNom");
  GLADE_HOOKUP_OBJECT (recherche, image33, "image33");
  GLADE_HOOKUP_OBJECT (recherche, hbox91, "hbox91");
  GLADE_HOOKUP_OBJECT (recherche, vbox45, "vbox45");
  GLADE_HOOKUP_OBJECT (recherche, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (recherche, schertreeviewChercher, "schertreeviewChercher");
  GLADE_HOOKUP_OBJECT (recherche, hbox92, "hbox92");
  GLADE_HOOKUP_OBJECT (recherche, vbox54, "vbox54");
  GLADE_HOOKUP_OBJECT (recherche, hbox104, "hbox104");
  GLADE_HOOKUP_OBJECT (recherche, vbox55, "vbox55");
  GLADE_HOOKUP_OBJECT (recherche, button23, "button23");
  GLADE_HOOKUP_OBJECT (recherche, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (recherche, hbox105, "hbox105");
  GLADE_HOOKUP_OBJECT (recherche, image27, "image27");
  GLADE_HOOKUP_OBJECT (recherche, label107, "label107");
  GLADE_HOOKUP_OBJECT (recherche, hbox106, "hbox106");
  GLADE_HOOKUP_OBJECT (recherche, button24, "button24");
  GLADE_HOOKUP_OBJECT (recherche, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (recherche, hbox107, "hbox107");
  GLADE_HOOKUP_OBJECT (recherche, image28, "image28");
  GLADE_HOOKUP_OBJECT (recherche, label108, "label108");
  GLADE_HOOKUP_OBJECT (recherche, button25, "button25");
  GLADE_HOOKUP_OBJECT (recherche, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (recherche, hbox108, "hbox108");
  GLADE_HOOKUP_OBJECT (recherche, image29, "image29");
  GLADE_HOOKUP_OBJECT (recherche, label109, "label109");
  GLADE_HOOKUP_OBJECT (recherche, vbox56, "vbox56");
  GLADE_HOOKUP_OBJECT (recherche, button26, "button26");
  GLADE_HOOKUP_OBJECT (recherche, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (recherche, hbox109, "hbox109");
  GLADE_HOOKUP_OBJECT (recherche, image30, "image30");
  GLADE_HOOKUP_OBJECT (recherche, label110, "label110");
  GLADE_HOOKUP_OBJECT (recherche, label111, "label111");
  GLADE_HOOKUP_OBJECT (recherche, vbox57, "vbox57");
  GLADE_HOOKUP_OBJECT (recherche, button27, "button27");
  GLADE_HOOKUP_OBJECT (recherche, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (recherche, hbox110, "hbox110");
  GLADE_HOOKUP_OBJECT (recherche, image31, "image31");
  GLADE_HOOKUP_OBJECT (recherche, label112, "label112");
  GLADE_HOOKUP_OBJECT (recherche, label113, "label113");
  GLADE_HOOKUP_OBJECT (recherche, image32, "image32");

  setup_treeview_columns(schertreeviewChercher);
  afficher_equipements(schertreeviewChercher, "equipements.txt");

  return recherche;
}

