/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AjouterUnMembre (void);
GtkWidget* create_demander_un_entraineur (void);
GtkWidget* create_gestion_des_membres (void);
GtkWidget* create_modifier__ (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_Espace_Administrateur (void);
GtkWidget* create_window2 (void);
GtkWidget* create_tache1 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
