/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout (void);
GtkWidget* create_reservation (void);
GtkWidget* create_modification (void);
GtkWidget* create_swarn (void);
GtkWidget* create_recherche (void);
