/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *AjouterUnMembre;
  GtkWidget *demander_un_entraineur;
  GtkWidget *gestion_des_membres;
  GtkWidget *modifier__;
  GtkWidget *supprimer;
  GtkWidget *Espace_Administrateur;
  GtkWidget *window2;
  GtkWidget *tache1;
  GtkWidget *window4;
  GtkWidget *window5;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  AjouterUnMembre = create_AjouterUnMembre ();
  gtk_widget_show (AjouterUnMembre);
  demander_un_entraineur = create_demander_un_entraineur ();
  gtk_widget_show (demander_un_entraineur);
  gestion_des_membres = create_gestion_des_membres ();
  gtk_widget_show (gestion_des_membres);
  modifier__ = create_modifier__ ();
  gtk_widget_show (modifier__);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  Espace_Administrateur = create_Espace_Administrateur ();
  gtk_widget_show (Espace_Administrateur);
  window2 = create_window2 ();
  gtk_widget_show (window2);
  tache1 = create_tache1 ();
  gtk_widget_show (tache1);
  window4 = create_window4 ();
  gtk_widget_show (window4);
  window5 = create_window5 ();
  gtk_widget_show (window5);

  gtk_main ();
  return 0;
}

